# Generated by Django 4.2.3 on 2024-04-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_booking_iscurrent_isoverdue_status_delete_reserved_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='ReservedStatus',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='reservedStatus',
        ),
    ]
